# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PHED
                                 A QGIS plugin
 This plugin generate PHED data in Jaltantra input format
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-12
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Swaril Singhal
        email                : 305swaril@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QMenu, QInputDialog
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, QgsWkbTypes, QgsVectorLayer, QgsApplication
from qgis.core import QgsVectorFileWriter, QgsPointXY, QgsPoint, QgsLayerTreeLayer
from qgis.core import QgsVectorDataProvider, QgsFeature, QgsGeometry, QgsField, QgsExpression
from qgis.PyQt.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMenu
from qgis.core import *
# from processing.tools.vector import VectorWriter

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .PHED_dialog import PHEDDialog
import os.path


class PHED:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PHED_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&PHED')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PHED', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.menu.addAction(action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/PHED/icon.png'
        self.menu = self.iface.mainWindow().findChild(QMenu, '&WNDS')
        # If the menu does not exist, create it!
        if not self.menu:
            self.menu = QMenu('&WNDS', self.iface.mainWindow().menuBar())
            self.menu.setObjectName('&WNDS')
            actions = self.iface.mainWindow().menuBar().actions()
            lastAction = actions[-1]
            self.iface.mainWindow().menuBar().insertMenu(lastAction, self.menu)
        self.add_action(
            icon_path,
            text=self.tr(u'PHED'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&PHED'),
                action)
            self.iface.removeToolBarIcon(action)

    def t0_Upload_Pipeline_Layer(self):
        pipes_file, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Select  PipeLine file ", "", '*.shp')
        self.dlg.lineEdit_21.setText(pipes_file)
        pipes_file = self.dlg.lineEdit_21.text()

        # Pipes = QgsVectorLayer(pipes_file, "pipes", "ogr")
        # layer = QgsVectorLayer(pipes_file, "my_layer", "delimitedtext")
        # QgsVectorFileWriter.writeAsVectorFormat(layer, "d:/b/my_shapes.shp", "CP1250", None, "ESRI Shapefile")
        # QgsProject.instance().addMapLayer(Pipes)
        # QgsMapLayerRegistry.instance().addMapLayer(layer)
        # self.dlg.progressBar.setValue(0)

    def t0_Upload_Node_Layer(self):
        proposed_nodes_file, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Select  Nodelayer file ", "", '*.csv')
        self.dlg.lineEdit_22.setText(proposed_nodes_file)
        proposed_nodes_file = self.dlg.lineEdit_22.text()
        crs = QgsCoordinateReferenceSystem("epsg:4326")

        PointLyr = QgsVectorLayer(proposed_nodes_file, "Nodes", "ogr")
        uri = proposed_nodes_file + "?delimiter=%s&xField=%s&yField=%s&decimal=%s" % (",", "Longitude", "Latitude", ".")
        layer = QgsVectorLayer(uri, "my_layer", "delimitedtext")
        dir_path = os.path.dirname(proposed_nodes_file)
        res_shap = dir_path + "/Nodes.shp"
        QgsVectorFileWriter.writeAsVectorFormat(layer, res_shap, "UTF-8", crs, "ESRI Shapefile")
        QgsProject.instance().addMapLayer(PointLyr)

        # self.dlg.progressBar.setValue(0)
        # spatRef = QgsCoordinateReferenceSystem(int(Coordinate_Reference_System.split(':')[1]), QgsCoordinateReferenceSystem.EpsgCrsId)
 
        # inp_tab = QgsVectorLayer(proposed_nodes_file, 'Input_Table', 'ogr')
        # prov = inp_tab.dataProvider()
        # fields = inp_tab.pendingFields()
        # outLayer = QgsVectorFileWriter(Output_Layer, None, fields, QGis.WKBPoint, spatRef)
 
        # pt = QgsPoint()
        # outFeature = QgsFeature()
 
        # for feat in inp_tab.getFeatures():
        #     attrs = feat.attributes()
        #     pt.setX(float(feat[Longitude]))
        #     pt.setY(float(feat[Latitude]))
        #     outFeature.setAttributes(attrs)
        #     outFeature.setGeometry(QgsGeometry.fromPoint(pt))
        #     outLayer.addFeature(outFeature)
        # del outLayer
        # QgsProject.instance().addMapLayer(inp_tab)

    def t0_Update_Pipeline_Layer(self):
        nodes_file = self.dlg.lineEdit_22.text()
        # ogr2ogr.main(["","-f", "ESRI Shapefile", "-s_srs", "epsg:32643", "-t_srs", "epsg:4326", "newp.shp", nodes_file])
        nodeLyr = QgsVectorLayer(nodes_file, "nodes", "ogr")
        pipes_file = self.dlg.lineEdit_21.text()
        # ogr2ogr.main(["","-f", "ESRI Shapefile", "-s_srs", "epsg:32643", "-t_srs", "epsg:4326", "newl.shp", pipes_file])
        # pipeLyr = QgsVectorLayer(pipes_file, "updated pipes", "ogr")
        vl = QgsVectorLayer("Point?crs=epsg:4326", "temporary_points", "memory")
        pr = vl.dataProvider()
        #setting up reprojection for temporary points
        # epsg4326 = QgsCoordinateReferenceSystem(
        #     4326,
        #     QgsCoordinateReferenceSystem.EpsgCrsId)
        # self.reprojectgeographic = QgsCoordinateTransform(
        #     self.iface.mapCanvas().mapSettings().destinationCrs(),
        #     epsg4326, QgsProject.instance())
        # QgsProject.instance().addMapLayer(pipeLyr)
        # spatRef = QgsCoordinateReferenceSystem(int(Coordinate_Reference_System.split(':')[1]), QgsCoordinateReferenceSystem.EpsgCrsId)
        spatRef = QgsCoordinateReferenceSystem(4326, QgsCoordinateReferenceSystem.EpsgCrsId)
 
        inp_tab = QgsVectorLayer(nodes_file, 'Input_Table', 'ogr')
        prov = inp_tab.dataProvider()
        fields = inp_tab.fields()
        outLayer = QgsVectorLayer(pipes_file, "nodes in zone", "ogr")
 
        pt = QgsPointXY()
        outFeature = QgsFeature()
 
        for feat in inp_tab.getFeatures():
            attrs = feat.attributes()
            pt.setX(float(feat["Longitude"]))
            pt.setY(float(feat["Latitude"]))
            outFeature.setAttributes(attrs)
            # outFeature.setGeometry(float(feat["Longitude"]),float(feat["Latitude"]))
            outFeature.setGeometry(QgsGeometry.fromPointXY(pt))
            outLayer.addFeature(outFeature)
        # del outLayer
        QgsProject.instance().addMapLayer(outLayer)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = PHEDDialog()
            self.dlg.pushButton_9.clicked.connect(self.t0_Upload_Node_Layer)
            self.dlg.pushButton_7.clicked.connect(self.t0_Upload_Pipeline_Layer)
            self.dlg.pushButton.clicked.connect(self.t0_Update_Pipeline_Layer)
            #zone wise feature selection
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
